"""
Created on Tuesday June 2 2020 17:28 +0700

@author: arunwpm
"""
import sys
import csv

def loadcsv(filename):
    with open(filename, newline='') as f: 
        return list(csv.reader(f))

def savecsv(filename, list):
    with open(filename, "w", newline="") as f:
        csv.writer(f).writerows(list)

if __name__ == "__main__":
    matloc = sys.argv[1] #first argument: name of the matrix (true / pred) file in the directory
    ldloc = 'labels_dict.csv' #name of the labels dictionary generated by nb.py (should be labels_dict.csv)
    id2tagloc = 'nyt-theme-tags.csv' #name of the conversion table from tag id to tag name for NYTcorpus

    mat = loadcsv(matloc)
    ld = loadcsv(ldloc)
    id2tag_table = loadcsv(id2tagloc)
    id2tag = {}
    for row in id2tag_table:
        if row == []:
            continue
        id2tag[row[1]] = row[2]

    out = []
    for row in mat:
        out.append([])
        rowlist = list(row)
        for i in range(len(rowlist)):
            if int(rowlist[i]) == 1:
                out[-1].append(id2tag[ld[i][1]])
    
    savecsv("tags_" + sys.argv[1], out)
